[workspace]
resolver = "2"
members = [
    "common",
    "camera_control",
    "game",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = { version = "0.12.0", features = ["dynamic_linking"] }
bevy_render = "0.12.0"
camera_control = { path = "camera_control" }
common = { path = "common" }